version: '3.8'
services:
  mysql-container:
    image: mysql:8.3.0
    environment:
      - MYSQL_ROOT_PASSWORD=admin
    ports:
      - "3307:3306"
    volumes:
      - ./mysql-init:/docker-entrypoint-initdb.d
    networks:
      - products-microservice-network
    hostname: mysql-host-productsmicroservice
  products-microservice:
    image: 900325302/ecommerce-products-microservice:v1.0
    environment:
      - MYSQL_HOST=mysql-host-productsmicroservice
      - MYSQL_PORT=3306
      - MYSQL_PASSWORD=admin
    ports:
      - "8082:8080"
    networks:
      - products-microservice-network
networks:
  products-microservice-network: